name: Build, Test, and Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Node Version
      uses: actions/setup-node@v4
      with:
        node-version: lts/iron

    - name: Install
      uses: bahmutov/npm-install@v1

    - name: Build
      run: |
        npm run build --if-present
      env:
        CI: true

    - name: Test
      run: |
        npm run ci --if-present
      env:
        CI: true

    - name: Build Docs
      run: |
        npm run build-docs --if-present
      env:
        CI: true

    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: dist/ngx-datatable
      if: ${{ github.ref == 'refs/heads/master' }}
